package core.products;

import core.enums.Continent;
import core.enums.Region;
import core.enums.Resource;

public class ProductFactory {

    public static Shop createShop() {
        return builder()
                .addProduct(Resource.GAZ_NATUREL, 40, 6400000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.ACIER, 30, 6600000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.PETROLE, 30, 7200000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.OR, 20, 400000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.BLE, 25, 5000000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.NICKEL, 30, 3600000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.FER, 30, 6000000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.ALUMINIUM, 20, 2800000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.HOUILLE, 20, 4400000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.CUIVRE, 15, 2700000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.COBALT, 20, 2400000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.LAINE_BRUTE, 20, 2000000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.PLOMB, 20, 2400000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.CONSTRUCTION_NAVALE, 10, 1400000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.SUCRE, 20, 3600000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.COTON_BRUT, 25, 2500000, null, Region.RUSSIE_CEI, Region.RUSSIE_CEI.getName())
                .addProduct(Resource.GAZ_NATUREL, 5, 800000, Continent.AFRICA, Region.MAGHREB, "Algérie")
                .addProduct(Resource.COBALT, 35, 4200000, Continent.AFRICA, Region.AFRIQUE_CENTRALE, "RD Congo")
                .addProduct(Resource.CAFE, 5, 400000, Continent.AFRICA, Region.AFRIQUE_NORD_EST, "Ethiopie")
                .addProduct(Resource.CUIVRE, 10, 1800000, Continent.AFRICA, Region.AFRIQUE_GRANDS_LACS, "Zambie")
                .addProduct(Resource.COBALT, 20, 2400000, Continent.AFRICA, Region.AFRIQUE_GRANDS_LACS, "Zambie")
                .addProduct(Resource.THE, 15, 1500000, Continent.AFRICA, Region.AFRIQUE_GRANDS_LACS, "Kenya")
                .addProduct(Resource.URANIUM, 10, 1600000, Continent.AFRICA, Region.AFRIQUE_SUD, "Namibie")
                .addProduct(Resource.OR, 40, 8000000, Continent.AFRICA, Region.AFRIQUE_SUD, Region.AFRIQUE_SUD.getName())
                .addProduct(Resource.HOUILLE, 5, 1100000, Continent.AFRICA, Region.AFRIQUE_SUD, Region.AFRIQUE_SUD.getName())
                .addProduct(Resource.LAINE_BRUTE, 5, 500000, Continent.AFRICA, Region.AFRIQUE_SUD, Region.AFRIQUE_SUD.getName())
                .addProduct(Resource.URANIUM, 10, 1600000, Continent.AFRICA, Region.AFRIQUE_OCCIDENTALE, "Niger")
                .addProduct(Resource.CACAO, 5, 400000, Continent.AFRICA, Region.AFRIQUE_OCCIDENTALE, "Cameroon")
                .addProduct(Resource.CACAO, 20, 1600000, Continent.AFRICA, Region.AFRIQUE_OCCIDENTALE, "Ghana")
                .addProduct(Resource.CACAO, 5, 400000, Continent.AFRICA, Region.AFRIQUE_OCCIDENTALE, "Nigeria")
                .addProduct(Resource.CACAO, 35, 2800000, Continent.AFRICA, Region.AFRIQUE_OCCIDENTALE, "Côte d'Ivoire")
                .addProduct(Resource.CAFE, 10, 800000, Continent.AFRICA, Region.AFRIQUE_OCCIDENTALE, "Côte d'Ivoire")
                .addProduct(Resource.FER, 10, 2000000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Australie")
                .addProduct(Resource.URANIUM, 10, 1600000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Australie")
                .addProduct(Resource.NICKEL, 10, 1200000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Australie")
                .addProduct(Resource.LAINE_BRUTE, 35, 3500000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Australie")
                .addProduct(Resource.LAINE_BRUTE, 15, 1500000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Nouvelle-Zélande")
                .addProduct(Resource.PLOMB, 20, 2400000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Australie")
                .addProduct(Resource.NICKEL, 10, 1200000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Nouvelle-Calédonie")
                .addProduct(Resource.ALUMINIUM, 10, 1400000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Australie")
                .addProduct(Resource.ARGENT, 15, 2100000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Australie")
                .addProduct(Resource.OR, 10, 2000000, Continent.ASIA_OCEANIA, Region.OCEANIE, "Australie - Fidji - Nouvelle-Guinée")
                .addProduct(Resource.CONSTRUCTION_AUTOMOBILE, 5, 800000, Continent.EUROPE, Region.EUROPE_MEDITERRANEENNE, "Italie")
                .addProduct(Resource.CONSTRUCTION_AUTOMOBILE, 5, 800000, Continent.EUROPE, Region.EUROPE_MEDITERRANEENNE, "Espagne")
                .addProduct(Resource.GAZ_NATUREL, 5, 800000, Continent.EUROPE, Region.ROYAUME_UNI, "Royaume-Uni")
                .addProduct(Resource.CONSTRUCTION_AUTOMOBILE, 15, 2400000, Continent.EUROPE, Region.FRANCE, Region.FRANCE.getName())
                .addProduct(Resource.URANIUM, 10, 1800000, Continent.EUROPE, Region.FRANCE, Region.FRANCE.getName())
                .addProduct(Resource.BLE, 10, 2000000, Continent.EUROPE, Region.FRANCE, Region.FRANCE.getName())
                .addProduct(Resource.CUIVRE, 5, 900000, Continent.EUROPE, Region.EUROPE_DANUBIENNE, "Pologne")
                .addProduct(Resource.HOUILLE, 5, 1100000, Continent.EUROPE, Region.EUROPE_DANUBIENNE, "Pologne")
                .addProduct(Resource.THE, 5, 500000, Continent.EUROPE, Region.EUROPE_BALKANIQUE, "Turquie")
                .addProduct(Resource.CONSTRUCTION_NAVALE, 5, 700000, Continent.EUROPE, Region.EUROPE_BALKANIQUE, "Ex-Yougoslavie")
                .addProduct(Resource.GAZ_NATUREL, 5, 800000, Continent.EUROPE, Region.BENELUX, "Pays-Bas")
                .addProduct(Resource.ALUMINIUM, 10, 1400000, Continent.EUROPE, Region.ALLEMAGNE, Region.ALLEMAGNE.getName())
                .addProduct(Resource.CONSTRUCTION_AUTOMOBILE, 20, 3200000, Continent.EUROPE, Region.ALLEMAGNE, Region.ALLEMAGNE.getName())
                .addProduct(Resource.ACIER, 10, 2200000, Continent.EUROPE, Region.ALLEMAGNE, Region.ALLEMAGNE.getName())
                .addProduct(Resource.CONSTRUCTION_NAVALE, 10, 1400000, Continent.EUROPE, Region.ALLEMAGNE, Region.ALLEMAGNE.getName())
                .addProduct(Resource.CONSTRUCTION_NAVALE, 5, 700000, Continent.EUROPE, Region.SCANDINAVIE, "Danemark")
                .addProduct(Resource.NICKEL, 10, 1200000, Continent.EUROPE, Region.SCANDINAVIE, "Norvège")
                .addProduct(Resource.COBALT, 5, 600000, Continent.EUROPE, Region.SCANDINAVIE, "Norvège")
                .addProduct(Resource.COBALT, 5, 600000, Continent.EUROPE, Region.SCANDINAVIE, "Finlande")
                .addProduct(Resource.PETROLE, 10, 2400000, Continent.ASIA_OCEANIA, Region.MOYEN_ORIENT, "Iran")
                .addProduct(Resource.PETROLE, 15, 3600000, Continent.ASIA_OCEANIA, Region.MOYEN_ORIENT, "Arabie Saoudite")
                .addProduct(Resource.CAOUTCHOUC_NATUREL, 5, 400000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDOCHINOISE, "Cambodge")
                .addProduct(Resource.CAOUTCHOUC_NATUREL, 20, 1600000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDOCHINOISE, "Thaïlande")
                .addProduct(Resource.CAOUTCHOUC_NATUREL, 35, 2800000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDOCHINOISE, "Malaisie")
                .addProduct(Resource.RIZ, 5, 700000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDOCHINOISE, "Thaïlande")
                .addProduct(Resource.RIZ, 5, 700000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDOCHINOISE, "Viet Nam")
                .addProduct(Resource.CACAO, 15, 1200000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDOCHINOISE, "Malaisie")
                .addProduct(Resource.ACIER, 20, 4400000, Continent.ASIA_OCEANIA, Region.JAPON, Region.JAPON.getName())
                .addProduct(Resource.CONSTRUCTION_NAVALE, 20, 2800000, Continent.ASIA_OCEANIA, Region.JAPON, "Corée")
                .addProduct(Resource.CONSTRUCTION_NAVALE, 50, 7000000, Continent.ASIA_OCEANIA, Region.JAPON, Region.JAPON.getName())
                .addProduct(Resource.NICKEL, 15, 1800000, Continent.ASIA_OCEANIA, Region.JAPON, Region.JAPON.getName())
                .addProduct(Resource.ALUMINIUM, 10, 1400000, Continent.ASIA_OCEANIA, Region.JAPON, Region.JAPON.getName())
                .addProduct(Resource.CONSTRUCTION_AUTOMOBILE, 30, 3800000, Continent.ASIA_OCEANIA, Region.JAPON, Region.JAPON.getName())
                .addProduct(Resource.RIZ, 10, 1400000, Continent.ASIA_OCEANIA, Region.JAPON, Region.JAPON.getName())
                .addProduct(Resource.CAOUTCHOUC_NATUREL, 30, 2400000, Continent.ASIA_OCEANIA, Region.INDONESIE, "Indonésie")
                .addProduct(Resource.CAOUTCHOUC_NATUREL, 5, 400000, Continent.ASIA_OCEANIA, Region.INDONESIE, "Philippines")
                .addProduct(Resource.THE, 5, 500000, Continent.ASIA_OCEANIA, Region.INDONESIE, "Indonésie")
                .addProduct(Resource.CAFE, 15, 1200000, Continent.ASIA_OCEANIA, Region.INDONESIE, "Indonésie")
                .addProduct(Resource.RIZ, 15, 2100000, Continent.ASIA_OCEANIA, Region.INDONESIE, "Indonésie")
                .addProduct(Resource.THE, 15, 150000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Sri Lanka")
                .addProduct(Resource.THE, 35, 350000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Inde")
                .addProduct(Resource.COTON_BRUT, 15, 1500000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Inde")
                .addProduct(Resource.COTON_BRUT, 10, 1000000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Pakistan")
                .addProduct(Resource.FER, 5, 1000000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Inde")
                .addProduct(Resource.HOUILLE, 5, 1100000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Inde")
                .addProduct(Resource.CAOUTCHOUC_NATUREL, 5, 400000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Inde")
                .addProduct(Resource.SUCRE, 25, 4500000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Inde")
                .addProduct(Resource.RIZ, 25, 3500000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Inde")
                .addProduct(Resource.BLE, 15, 3000000, Continent.ASIA_OCEANIA, Region.PENINSULE_INDIENNE, "Inde")
                .addProduct(Resource.BLE, 25, 5000000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.FER, 20, 4000000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.HOUILLE, 35, 7700000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.RIZ, 40, 5600000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.LAINE_BRUTE, 15, 1500000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.ACIER, 15, 3300000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.COTON_BRUT, 25, 2500000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.PLOMB, 15, 1800000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.SUCRE, 10, 1800000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.THE, 25, 2500000, Continent.ASIA_OCEANIA, Region.CHINE, Region.CHINE.getName())
                .addProduct(Resource.FER, 5, 1000000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.PETROLE, 25, 6000000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.OR, 15, 3000000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.HOUILLE, 25, 5500000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.CUIVRE, 25, 4500000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.GAZ_NATUREL, 25, 4800000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.CONSTRUCTION_AUTOMOBILE, 25, 4000000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.ALUMINIUM, 35, 4900000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.COTON_BRUT, 20, 2000000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.ARGENT, 20, 2800000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.PLOMB, 20, 2400000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.URANIUM, 15, 2400000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.ACIER, 15, 3300000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.BLE, 15, 3000000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.SUCRE, 10, 1800000, null, Region.USA, Region.USA.getName())
                .addProduct(Resource.SUCRE, 20, 3600000, Continent.AMERICA, Region.ANTILLES, "Cuba")
                .addProduct(Resource.ARGENT, 25, 3500000, Continent.AMERICA, Region.MEXIQUE, Region.MEXIQUE.getName())
                .addProduct(Resource.CAFE, 10, 800000, Continent.AMERICA, Region.MEXIQUE, Region.MEXIQUE.getName())
                .addProduct(Resource.PETROLE, 10, 2400000, Continent.AMERICA, Region.MEXIQUE, Region.MEXIQUE.getName())
                .addProduct(Resource.LAINE_BRUTE, 10, 1000000, Continent.AMERICA, Region.ARGENTINE, Region.ARGENTINE.getName())
                .addProduct(Resource.CUIVRE, 25, 4500000, Continent.AMERICA, Region.PAYS_ANDINS, "Chili")
                .addProduct(Resource.CAFE, 25, 2000000, Continent.AMERICA, Region.PAYS_ANDINS, "Colombie")
                .addProduct(Resource.ARGENT, 20, 2800000, Continent.AMERICA, Region.PAYS_ANDINS, "Pérou")
                .addProduct(Resource.PLOMB, 10, 1200000, Continent.AMERICA, Region.PAYS_ANDINS, "Pérou")
                .addProduct(Resource.ARGENT, 5, 700000, Continent.AMERICA, Region.PAYS_ANDINS, "Bolivie")
                .addProduct(Resource.PETROLE, 5, 1200000, Continent.AMERICA, Region.VENEZUELA, Region.VENEZUELA.getName())
                .addProduct(Resource.CAFE, 35, 2800000, Continent.AMERICA, Region.BRESIL, Region.BRESIL.getName())
                .addProduct(Resource.FER, 25, 5000000, Continent.AMERICA, Region.BRESIL, Region.BRESIL.getName())
                .addProduct(Resource.CACAO, 20, 1600000, Continent.AMERICA, Region.BRESIL, Region.BRESIL.getName())
                .addProduct(Resource.SUCRE, 15, 2700000, Continent.AMERICA, Region.BRESIL, Region.BRESIL.getName())
                .addProduct(Resource.OR, 5, 1000000, Continent.AMERICA, Region.BRESIL, Region.BRESIL.getName())
                .addProduct(Resource.ACIER, 5, 1100000, Continent.AMERICA, Region.BRESIL, Region.BRESIL.getName())
                .addProduct(Resource.COTON_BRUT, 5, 500000, Continent.AMERICA, Region.BRESIL, Region.BRESIL.getName())
                .addProduct(Resource.URANIUM, 40, 6400000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.NICKEL, 25, 3000000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.CUIVRE, 15, 2700000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.PLOMB, 15, 1800000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.ARGENT, 15, 2100000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.ALUMINIUM, 15, 2100000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.BLE, 10, 2000000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.OR, 10, 2000000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.GAZ_NATUREL, 10, 1600000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .addProduct(Resource.COBALT, 10, 1200000, Continent.AMERICA, Region.CANADA, Region.CANADA.getName())
                .build();
    }

    public static ShopBuilder builder() { return new ShopBuilder(); }

    public static class ShopBuilder {

        private final Shop shop;

        public ShopBuilder() {
            this.shop = new Shop();
        }

        public ShopBuilder addProduct(Resource resource, int percentage, int price, Continent continent, Region region, String country) {
            shop.addProduct(new Product(resource, percentage, price, continent, region, country));
            return this;
        }

        public Shop build() {
            return shop;
        }
    }
}
